export const ENV = {
    hosts:{
        trade: 'https://trade.aiyongtech.com',
        mtrade: 'https://mtrade.aiyongtech.com',
        item:'https://item.aiyongtech.com',
        mitem:'https://mitem.aiyongtech.com',
        default: 'https://mitem.aiyongtech.com',
        mdefault:'https://mitem.aiyongtech.com',
    },
    planet:"interactmapp",
    device:'mobile',
    app:'interact',
    appName:'爱用互动',
    appid: "3000000012505562",
    platform:'mapp',
    entryApiName:'aiyong.interact.user.info.get',
    userApiName:'aiyong.interactc.user.data.set',
    userMethod: '/interactive/setInertActCUserData',
    version: '0.0.1',
};
